Update Jenkinsfile

diff --git a/bank_app/Jenkinsfile b/bank_app/Jenkinsfile
--- a/bank_app/Jenkinsfile
+++ b/bank_app/Jenkinsfile
@@ -1,20 +1,24 @@
 pipeline {
     agent {
         kubernetes {
+            defaultContainer 'kubectl'
             yaml '''
 apiVersion: v1
 kind: Pod
 spec:
   serviceAccountName: jenkins
+
   containers:
+  - name: jnlp
+    image: jenkins/inbound-agent:latest-jdk21
+    args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
+
   - name: kubectl
-    image: bitnami/kubectl:latest
+    image: bitnami/kubectl:1.33
     command:
-    - sleep
-    args:
-    - infinity
+      - cat
+    tty: true
 '''
-            defaultContainer 'kubectl'
         }
     }
 
@@ -28,41 +32,66 @@ spec:
 
         stage('Deploy Application') {
             steps {
-                withVault(
-                    configuration: [
-                        vaultUrl: 'http://vault.vault:8200',
-                        vaultCredentialId: 'vault-k8s',
-                        engineVersion: 2
-                    ],
-                    vaultSecrets: [[
-                        path: 'secret/bank_app',
-                        secretValues: [
-                            [vaultKey: 'token',  envVar: 'KUBE_TOKEN'],
-                            [vaultKey: 'server', envVar: 'KUBE_SERVER'],
-                            [vaultKey: 'ca.crt', envVar: 'KUBE_CA']
-                        ]
-                    ]]
-                ) {
+                container('kubectl') {
+                    withVault(
+                        configuration: [
+                            vaultUrl: 'http://vault.vault:8200',
+                            vaultCredentialId: 'vault-k8s',
+                            engineVersion: 2
+                        ],
+                        vaultSecrets: [[
+                            path: 'secret/bank_app',
+                            secretValues: [
+                                [vaultKey: 'token',  envVar: 'KUBE_TOKEN'],
+                                [vaultKey: 'server', envVar: 'KUBE_SERVER'],
+                                [vaultKey: 'ca.crt', envVar: 'KUBE_CA']
+                            ]
+                        ]]
+                    ) {
 
-                    sh '''
-                        echo "$KUBE_CA" > ca.crt
+                        sh '''
+                            set -e
 
-                        kubectl \
-                          --server="$KUBE_SERVER" \
-                          --token="$KUBE_TOKEN" \
-                          --certificate-authority=ca.crt \
-                          apply -f bank_app/
+                            echo "$KUBE_CA" > ca.crt
 
-                        kubectl \
-                          --server="$KUBE_SERVER" \
-                          --token="$KUBE_TOKEN" \
-                          --certificate-authority=ca.crt \
-                          rollout status deployment/bankapp \
-                          -n bankapp \
-                          --timeout=300s
-                    '''
+                            echo "Checking kubectl..."
+                            kubectl version --client
+
+                            echo "Applying manifests..."
+
+                            kubectl \
+                              --server="$KUBE_SERVER" \
+                              --token="$KUBE_TOKEN" \
+                              --certificate-authority=ca.crt \
+                              apply -f bank_app/
+
+                            echo "Waiting for rollout..."
+
+                            kubectl \
+                              --server="$KUBE_SERVER" \
+                              --token="$KUBE_TOKEN" \
+                              --certificate-authority=ca.crt \
+                              rollout status deployment/bankapp \
+                              -n bankapp \
+                              --timeout=300s
+                        '''
+                    }
                 }
             }
+        }
+    }
+
+    post {
+        always {
+            cleanWs()
+        }
+
+        success {
+            echo "Application deployed successfully."
+        }
+
+        failure {
+            echo "Application deployment failed."
         }
     }
 }
